// Code generated by visitor_generator. DO NOT EDIT.
package ast

type SomethingAcceptor interface {
	AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something
}

type AnotherAcceptor interface {
	AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another
}

//Accept calls v.VisitRHSNewPair(r)
func (r RHSNewPair) AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another {
	return v.VisitRHSNewPair(r, ctx)
}

//Accept calls v.VisitRHSFunctionCall(r)
func (r RHSFunctionCall) AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another {
	return v.VisitRHSFunctionCall(r, ctx)
}

//Accept calls v.VisitPairElem(p)
func (p PairElem) AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another {
	return v.VisitPairElem(p, ctx)
}

//Accept calls v.VisitMake(m)
func (m Make) AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another {
	return v.VisitMake(m, ctx)
}

//Accept calls v.VisitBinOp(b)
func (b BinOp) AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another {
	return v.VisitBinOp(b, ctx)
}

//Accept calls v.VisitStatLock(s)
func (s StatLock) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatLock(s, ctx)
}

//Accept calls v.VisitStatSema(s)
func (s StatSema) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatSema(s, ctx)
}

//Accept calls v.VisitArrayElem(a)
func (a ArrayElem) AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another {
	return v.VisitArrayElem(a, ctx)
}

//Accept calls v.VisitIdent(i)
func (i Ident) AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another {
	return v.VisitIdent(i, ctx)
}

//Accept calls v.VisitFunction(f)
func (f Function) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitFunction(f, ctx)
}

//Accept calls v.VisitParamList(p)
func (p ParamList) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitParamList(p, ctx)
}

//Accept calls v.VisitParam(p)
func (p Param) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitParam(p, ctx)
}

//Accept calls v.VisitProgram(p)
func (p Program) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitProgram(p, ctx)
}

//Accept calls v.VisitStatSkip(s)
func (s StatSkip) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatSkip(s, ctx)
}

//Accept calls v.VisitStatRead(s)
func (s StatRead) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatRead(s, ctx)
}

//Accept calls v.VisitStatFree(s)
func (s StatFree) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatFree(s, ctx)
}

//Accept calls v.VisitStatNewassign(s)
func (s StatNewassign) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatNewassign(s, ctx)
}

//Accept calls v.VisitStatPrint(s)
func (s StatPrint) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatPrint(s, ctx)
}

//Accept calls v.VisitStatPrintln(s)
func (s StatPrintln) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatPrintln(s, ctx)
}

//Accept calls v.VisitStatExit(s)
func (s StatExit) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatExit(s, ctx)
}

//Accept calls v.VisitStatFor(s)
func (s StatFor) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatFor(s, ctx)
}

//Accept calls v.VisitStatWhile(s)
func (s StatWhile) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatWhile(s, ctx)
}

//Accept calls v.VisitStatDoWhile(s)
func (s StatDoWhile) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatDoWhile(s, ctx)
}

//Accept calls v.VisitStatBegin(s)
func (s StatBegin) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatBegin(s, ctx)
}

//Accept calls v.VisitStatAssign(s)
func (s StatAssign) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatAssign(s, ctx)
}

//Accept calls v.VisitStatReturn(s)
func (s StatReturn) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatReturn(s, ctx)
}

//Accept calls v.VisitStatIf(s)
func (s StatIf) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatIf(s, ctx)
}

//Accept calls v.VisitWaccRoutine(w)
func (w WaccRoutine) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitWaccRoutine(w, ctx)
}

//Accept calls v.VisitStatMultiple(s)
func (s StatMultiple) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitStatMultiple(s, ctx)
}

//Accept calls v.VisitTernaryOp(t)
func (t TernaryOp) AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another {
	return v.VisitTernaryOp(t, ctx)
}

//Accept calls v.VisitLiteral(l)
func (l Literal) AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another {
	return v.VisitLiteral(l, ctx)
}

//Accept calls v.VisitUnOp(u)
func (u UnOp) AcceptAnother(v SomethingAnotherVisitor, ctx Ctx) Another {
	return v.VisitUnOp(u, ctx)
}

//Accept calls v.VisitUserType(u)
func (u UserType) AcceptSomething(v SomethingAnotherVisitor, ctx Ctx) Something {
	return v.VisitUserType(u, ctx)
}
