// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Code generated by visitor_generator. DO NOT EDIT.
package ast

import "wacc_32/assembly/instructions"

//InstructionExprInstrVisitor is an AST visitor that returns instructions.ExprInstr for expressions and instructions.Instruction for everything elsd
type InstructionExprInstrVisitor interface {

	//VisitRHS visits AST node RHS
	VisitRHS(node RHS, ctx *instructions.Context) instructions.ExprInstr

	//VisitExpression visits AST node Expression
	VisitExpression(node Expression, ctx *instructions.Context) instructions.ExprInstr

	//VisitStatement visits AST node Statement
	VisitStatement(node Statement, ctx *instructions.Context) instructions.Instruction

	//VisitAST visits AST node AST
	VisitAST(node AST, ctx *instructions.Context) instructions.Instruction

	//VisitRHSNewPair visits AST node RHSNewPair
	VisitRHSNewPair(node RHSNewPair, ctx *instructions.Context) instructions.ExprInstr

	//VisitRHSFunctionCall visits AST node RHSFunctionCall
	VisitRHSFunctionCall(node RHSFunctionCall, ctx *instructions.Context) instructions.ExprInstr

	//VisitPairElem visits AST node PairElem
	VisitPairElem(node PairElem, ctx *instructions.Context) instructions.ExprInstr

	//VisitMake visits AST node Make
	VisitMake(node Make, ctx *instructions.Context) instructions.ExprInstr

	//VisitBinOp visits AST node BinOp
	VisitBinOp(node BinOp, ctx *instructions.Context) instructions.ExprInstr

	//VisitStatLock visits AST node StatLock
	VisitStatLock(node StatLock, ctx *instructions.Context) instructions.Instruction

	//VisitStatSema visits AST node StatSema
	VisitStatSema(node StatSema, ctx *instructions.Context) instructions.Instruction

	//VisitArrayElem visits AST node ArrayElem
	VisitArrayElem(node ArrayElem, ctx *instructions.Context) instructions.ExprInstr

	//VisitIdent visits AST node Ident
	VisitIdent(node Ident, ctx *instructions.Context) instructions.ExprInstr

	//VisitFunction visits AST node Function
	VisitFunction(node Function, ctx *instructions.Context) instructions.Instruction

	//VisitParamList visits AST node ParamList
	VisitParamList(node ParamList, ctx *instructions.Context) instructions.Instruction

	//VisitParam visits AST node Param
	VisitParam(node Param, ctx *instructions.Context) instructions.Instruction

	//VisitProgram visits AST node Program
	VisitProgram(node Program, ctx *instructions.Context) instructions.Instruction

	//VisitStatSkip visits AST node StatSkip
	VisitStatSkip(node StatSkip, ctx *instructions.Context) instructions.Instruction

	//VisitStatRead visits AST node StatRead
	VisitStatRead(node StatRead, ctx *instructions.Context) instructions.Instruction

	//VisitStatFree visits AST node StatFree
	VisitStatFree(node StatFree, ctx *instructions.Context) instructions.Instruction

	//VisitStatNewassign visits AST node StatNewassign
	VisitStatNewassign(node StatNewassign, ctx *instructions.Context) instructions.Instruction

	//VisitStatPrint visits AST node StatPrint
	VisitStatPrint(node StatPrint, ctx *instructions.Context) instructions.Instruction

	//VisitStatPrintln visits AST node StatPrintln
	VisitStatPrintln(node StatPrintln, ctx *instructions.Context) instructions.Instruction

	//VisitStatExit visits AST node StatExit
	VisitStatExit(node StatExit, ctx *instructions.Context) instructions.Instruction

	//VisitStatFor visits AST node StatFor
	VisitStatFor(node StatFor, ctx *instructions.Context) instructions.Instruction

	//VisitStatWhile visits AST node StatWhile
	VisitStatWhile(node StatWhile, ctx *instructions.Context) instructions.Instruction

	//VisitStatDoWhile visits AST node StatDoWhile
	VisitStatDoWhile(node StatDoWhile, ctx *instructions.Context) instructions.Instruction

	//VisitStatBegin visits AST node StatBegin
	VisitStatBegin(node StatBegin, ctx *instructions.Context) instructions.Instruction

	//VisitStatAssign visits AST node StatAssign
	VisitStatAssign(node StatAssign, ctx *instructions.Context) instructions.Instruction

	//VisitStatReturn visits AST node StatReturn
	VisitStatReturn(node StatReturn, ctx *instructions.Context) instructions.Instruction

	//VisitStatIf visits AST node StatIf
	VisitStatIf(node StatIf, ctx *instructions.Context) instructions.Instruction

	//VisitWaccRoutine visits AST node WaccRoutine
	VisitWaccRoutine(node WaccRoutine, ctx *instructions.Context) instructions.Instruction

	//VisitStatMultiple visits AST node StatMultiple
	VisitStatMultiple(node StatMultiple, ctx *instructions.Context) instructions.Instruction

	//VisitTernaryOp visits AST node TernaryOp
	VisitTernaryOp(node TernaryOp, ctx *instructions.Context) instructions.ExprInstr

	//VisitLiteral visits AST node Literal
	VisitLiteral(node Literal, ctx *instructions.Context) instructions.ExprInstr

	//VisitUnOp visits AST node UnOp
	VisitUnOp(node UnOp, ctx *instructions.Context) instructions.ExprInstr

	//VisitUserType visits AST node UserType
	VisitUserType(node UserType, ctx *instructions.Context) instructions.Instruction
}
