// Code generated by "stringer -type=Cond"; DO NOT EDIT.

package instructions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EQ-1]
	_ = x[NE-2]
	_ = x[GT-3]
	_ = x[LE-4]
	_ = x[GE-5]
	_ = x[LT-6]
	_ = x[AL-7]
	_ = x[NV-8]
	_ = x[VS-9]
}

const _Cond_name = "EQNEGTLEGELTALNVVS"

var _Cond_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18}

func (i Cond) String() string {
	i -= 1
	if i < 0 || i >= Cond(len(_Cond_index)-1) {
		return "Cond(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Cond_name[_Cond_index[i]:_Cond_index[i+1]]
}
