// Code generated by "stringer -type=StackInstrType"; DO NOT EDIT.

package instructions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[push-1]
	_ = x[pop-2]
}

const _StackInstrType_name = "pushpop"

var _StackInstrType_index = [...]uint8{0, 4, 7}

func (i StackInstrType) String() string {
	i -= 1
	if i < 0 || i >= StackInstrType(len(_StackInstrType_index)-1) {
		return "StackInstrType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _StackInstrType_name[_StackInstrType_index[i]:_StackInstrType_index[i+1]]
}
